//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehiculo_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matricula
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int vehiculo { get; set; }
        public byte agencia { get; set; }
        public short anio { get; set; }
    
        public virtual agencia agencia1 { get; set; }
        public virtual agencia agencia2 { get; set; }
        public virtual vehiculo vehiculo1 { get; set; }
        public virtual vehiculo vehiculo2 { get; set; }
    }
}
