//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehiculo_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculo()
        {
            this.matricula = new HashSet<matricula>();
            this.matricula1 = new HashSet<matricula>();
        }
    
        public int id { get; set; }
        public string placa { get; set; }
        public short marca { get; set; }
        public string motor { get; set; }
        public string chasis { get; set; }
        public string combustible { get; set; }
        public short anio { get; set; }
        public short color { get; set; }
        public string foto { get; set; }
        public decimal avaluo { get; set; }
    
        public virtual color color1 { get; set; }
        public virtual color color2 { get; set; }
        public virtual marca marca1 { get; set; }
        public virtual marca marca2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula1 { get; set; }
    }


}
