//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehiculo_CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehiculoMatricula_BDEntities : DbContext
    {
        public VehiculoMatricula_BDEntities()
            : base("name=VehiculoMatricula_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agencia> agencia { get; set; }
        public virtual DbSet<color> color { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<matricula> matricula { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
